### ISSUE TITLE
All lights are off when the build is in progress

### ISSUE THREAD

**Issue by eduardomhg** [4tecture/BuildTrafficLights#1]
From the description I understand that when a build is in progress all 3 lights should be blinking, but they are all off.

**Comment by eduardomhg** [comment]
Actually I just realized that it works fine if the dashboard is open when the builds starts. But if you open it when it is already in progress or press F5 all lights are off.

**Comment by marc-mueller** [comment]
Hi @eduardomhg ,

Thank you for reporting the issue. We will have a look at it and come back to you again.

Best regards,
Marc

**Comment by jawn** [comment]
I see the same when using VSTS.

**Comment by jawn** [comment]
Any news?

**Comment by marc-mueller** [comment]
Hi Guys

Sorry for my late answer, we uploaded a minor fix last week. Did you already update the extension?

**Comment by jawn** [comment]
Thanks Marc, we'll check it out.

**Comment by jawn** [comment]
I confirm, it's fixed now. Thanks!
