### ISSUE TITLE
"No builds available" message is displayed for stakeholder users

### ISSUE THREAD

**Issue by jawn** [4tecture/BuildTrafficLights#2]
Since stakeholders have no access to build information, the message "No builds available" is displayed instead of the traffic lights by the Build Traffic Lights extension.

Is it possible to improve the error message in this case?

**Comment by jawn** [comment]
Any news?

**Comment by marc-mueller** [comment]
I'll need to check that. A stakeholder does not have any access on this particular api and therefore cannot see any build information. So the message is correct for this user. The user does not have any builds available. We need to check if we can decide if it is based on the stakeholder access rights or if there are really no builds for this definition.

**Comment by jawn** [comment]
That makes sense

**Comment by marc-mueller** [comment]
Stakeholder permissions do not allow to interact with build api, so we cannot show any information.
