### ISSUE TITLE
Error Loading widget after TFS 2017 upgrade

### ISSUE THREAD

**Issue by kknapp1** [4tecture/BuildTrafficLights#4]
love the widget! but having errors since we upgraded on-prem TFS 2015 to TFS 2017.1. Error is "Widget failed to Load". We uninstalled from TFS and subsequently downloaded and installed the latest version (Version 0.1.20 Last updated 5/16/2017, 4:38:36 PM) with same results. Have you seen this before? Any ideas?

**Comment by marc-mueller** [comment]
Hi @kknapp1 

Sorry to hear that. No, we didn't experienced the same error and never heard of it. Did you check the browser console log if there is any additional information available?

**Comment by kknapp1** [comment]
Thanks, Marc. It's working now - found some other authentication issues with our TFS server that were causing this symptom. Still working those out but this plugin is working fine. Not an issue here. Thanks for the follow-up.
